#SPDX-License-Identifier: MIT-0
---
- name: Join control plane
  command: "{{ hostvars[groups['bootstrap_master'][0]].master_join }} --apiserver-advertise-address={{ node_IP }}"
  args:
    creates: /etc/kubernetes/kubelet.conf