#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/common
- name: Example from an Ansible Playbook
  ansible.builtin.ping:
- name: Update /etc/hosts for all cluster nodes
  blockinfile:
    path: /etc/hosts
    block: |      
      {% for host in groups['all'] %}
      {{ hostvars[host]['node_IP'] }}  {{ host }}.{{ cluster_domain }} {{ host }}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED CLUSTER HOSTS"
- name: Update apt
  apt:
    update_cache: yes
- name: Install pip (if missing)
  apt:
    name: python3-pip
    state: present    
- name: Install kubernetes package
  pip:
    name: kubernetes
    executable: pip3
